[package]
authors = ["Jonathan Creekmore <jonathan@thecreekmores.org>"]
name = "do_digest"
version = "0.1.0"

[dependencies]
digest = "0.6.0"
sha2 = "0.6.0"

[dependencies.do_digest_derive]
path = "../do_digest_derive"
